version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-fe-dev
      args:
        BACKEND_URL: http://backend:8080
    volumes:
      - type: bind
        source: ./src/main/webapp/reactjs/src
        target: /app/src
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
    command: npm start
    tty: true
    ports:
      - "3000:3000"
    links:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile-be
    environment:
      - DB_URL=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=db_password
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=db_password
    # volumes:
    #   - db-data:/var/lib/postgresql/data

# volumes:
#   db-data:
