FROM maven:3.8-openjdk-17-slim as build

COPY . /app

WORKDIR /app

RUN mvn clean install -Dmaven.test.skip=true

FROM openjdk:17

WORKDIR /app

COPY --from=build /app/target/*.jar .

CMD java -jar *.jar
